# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1305, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.zoom_in = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_in.setGeometry(QtCore.QRect(1140, 40, 75, 23))
        self.zoom_in.setObjectName("zoom_in")
        self.zoom_out = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_out.setGeometry(QtCore.QRect(1220, 40, 75, 23))
        self.zoom_out.setObjectName("zoom_out")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 891, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.roles = QtWidgets.QTreeWidget(self.centralwidget)
        self.roles.setGeometry(QtCore.QRect(1040, 90, 256, 501))
        self.roles.setObjectName("roles")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1100, 10, 81, 16))
        self.label.setObjectName("label")
        self.tranining_mode = QtWidgets.QLineEdit(self.centralwidget)
        self.tranining_mode.setGeometry(QtCore.QRect(1180, 10, 113, 22))
        self.tranining_mode.setObjectName("tranining_mode")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 720, 891, 61))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 881, 51))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.equipment_status = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.equipment_status.setContentsMargins(0, 0, 0, 0)
        self.equipment_status.setObjectName("equipment_status")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(900, 660, 391, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.alerts = QtWidgets.QTextEdit(self.groupBox_2)
        self.alerts.setGeometry(QtCore.QRect(10, 20, 371, 101))
        self.alerts.setObjectName("alerts")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 26))
        self.menubar.setObjectName("menubar")
        self.menuCACA = QtWidgets.QMenu(self.menubar)
        self.menuCACA.setObjectName("menuCACA")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCACA.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.zoom_in.setText(_translate("MainWindow", "+"))
        self.zoom_out.setText(_translate("MainWindow", "-"))
        self.roles.headerItem().setText(0, _translate("MainWindow", "Roles"))
        self.label.setText(_translate("MainWindow", "Training Mode:"))
        self.groupBox.setTitle(_translate("MainWindow", "Unmuted Equipment"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.menuCACA.setTitle(_translate("MainWindow", "CACA"))
