# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'catiz.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1305, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.zoom_in = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_in.setGeometry(QtCore.QRect(1100, 40, 75, 23))
        self.zoom_in.setObjectName("zoom_in")
        self.zoom_out = QtWidgets.QPushButton(self.centralwidget)
        self.zoom_out.setGeometry(QtCore.QRect(1180, 40, 75, 23))
        self.zoom_out.setObjectName("zoom_out")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 891, 721))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.set_center = QtWidgets.QPushButton(self.centralwidget)
        self.set_center.setGeometry(QtCore.QRect(1100, 10, 93, 28))
        self.set_center.setObjectName("set_center")
        self.roles = QtWidgets.QTreeWidget(self.centralwidget)
        self.roles.setGeometry(QtCore.QRect(1040, 90, 256, 501))
        self.roles.setObjectName("roles")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1305, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.zoom_in.setText(_translate("MainWindow", "+"))
        self.zoom_out.setText(_translate("MainWindow", "-"))
        self.set_center.setText(_translate("MainWindow", "Set Center"))
        self.roles.headerItem().setText(0, _translate("MainWindow", "Roles"))
